version: '3.5'
services:
    nginx-http:
        image: nginx:alpine
        ports:
            - 80:80
    nginx:
        depends_on:
            - nginx-http
        image: nginx:alpine
        ports:
            - 443:443
        volumes:
          - type: bind
            source: ./ssl.conf
            target: /etc/nginx/conf.d/ssl.conf
          - type: bind
            source: ./certs/example.org.crt
            target: /etc/ssl/certs/example.org.crt
          - type: bind
            source: ./certs/example.org.key
            target: /etc/ssl/private/example.org.key

